CREATE SCHEMA IF NOT EXISTS bronze;

CREATE TABLE IF NOT EXISTS bronze.hh_vacancies_details_bronze (
    id BIGINT PRIMARY KEY,

    premium BOOLEAN,
    billing_type JSONB,
    relations JSONB,
    name TEXT,
    insider_interview JSONB,
    response_letter_required BOOLEAN,
    area JSONB,
    salary JSONB,
    salary_range JSONB,
    type JSONB,
    address JSONB,
    allow_messages BOOLEAN,
    experience JSONB,
    schedule JSONB,
    employment JSONB,
    department JSONB,
    show_contacts BOOLEAN,
    contacts JSONB,
    description TEXT,
    branded_description TEXT,
    vacancy_constructor_template JSONB,
    key_skills JSONB,
    auto_response JSONB,
    accept_handicapped BOOLEAN,
    accept_kids BOOLEAN,
    age_restriction TEXT,
    archived BOOLEAN,
    response_url TEXT,
    specializations JSONB,
    professional_roles JSONB,
    code TEXT,
    hidden BOOLEAN,
    quick_responses_allowed BOOLEAN,
    driver_license_types JSONB,
    accept_incomplete_resumes BOOLEAN,
    employer JSONB,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    initial_created_at TIMESTAMPTZ,
    negotiations_url TEXT,
    suitable_resumes_url TEXT,
    apply_alternate_url TEXT,
    has_test BOOLEAN,
    test JSONB,
    alternate_url TEXT,
    working_days JSONB,
    working_time_intervals JSONB,
    working_time_modes JSONB,
    accept_temporary BOOLEAN,
    languages JSONB,
    approved BOOLEAN,
    employment_form JSONB,
    fly_in_fly_out_duration JSONB,
    internship BOOLEAN,
    night_shifts BOOLEAN,
    work_format JSONB,
    work_schedule_by_days JSONB,
    working_hours JSONB,
    show_logo_in_search BOOLEAN,
    closed_for_applicants BOOLEAN,
    search_profile TEXT,
    expected_risk_category TEXT,
    load_dt DATE,
    load_type TEXT,
    batch_idx INT,
    inserted_at TIMESTAMPTZ DEFAULT now()
);
