version: 2

models:
  - name: stg_hh__vacancy_details
    description: "Staging view for HH vacancy details from Bronze. No business logic; only column selection + traceability metadata."
    columns:
      - name: vacancy_id
        description: "HH vacancy id (business key)."
        tests:
          - not_null
          - unique

      - name: load_dt
        description: "Logical load date of ingestion batch (used for replay / partitioning)."
        tests:
          - not_null

      - name: search_profile
        description: "Search profile tag injected during ingestion (config-driven)."

      - name: expected_risk_category
        description: "Expected risk category injected during ingestion (compliance labeling)."
  - name: stg_hh__employers
    description: "Staging view for employers extracted from vacancy_details.employer_json. One row per employer_id (latest by load_dt/inserted_at)."
    columns:
      - name: employer_id
        description: "HH employer id (business key)."
        tests:
          - not_null
          - unique

      - name: employer_name
        description: "Employer name."

      - name: source_load_dt
        description: "Logical load date used to choose latest employer record."
        tests:
          - not_null

  - name: stg_hh__vacancy_skills
    description: "Staging view: exploded skills from vacancy_details.key_skills_json. Grain: one row per (vacancy_id, skill_name)."
    columns:
      - name: vacancy_id
        description: "HH vacancy id."
        tests:
          - not_null

      - name: skill_name
        description: "Skill name from HH key_skills array."
        tests:
          - not_null

      - name: source_load_dt
        description: "Logical load date for lineage."
        tests:
          - not_null

